# Base Image
FROM python:3.7

# create and set working directory
RUN mkdir /app
WORKDIR /app

# Add current directory code to working directory
ADD . /app/

# set default environment variables
ENV PYTHONUNBUFFERED 1
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        tzdata \
        python3-setuptools \
        python3-pip \
        python3-dev \
        python3-venv \
        git \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# install environment dependencies
RUN pip3 install --upgrade pip

# Install project dependencies
COPY requirements.txt /app/
COPY manage.py /app/
#COPY .env /app/

RUN pip install -r requirements.txt
RUN ./manage.py makemigrations && ./manage.py migrate

#EXPOSE 8888
CMD gunicorn api_backend.wsgi:application --bind 0.0.0.0:8000